version: '3.7'

services:
  main:
    container_name: main
    environment:
      - NODE_ENV=production
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    command: npm run start:${NODE_ENV}
    env_file:
      - .env
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017